### ISSUE TITLE
missing function and structure documentation 

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/navigator-rs#11]

**Comment by RaulTrombin** [comment]
Some start point is done. Please check PR's

[Create a channel stantard](https://github.com/bluerobotics/navigator-rs/pull/14)
[Docs - Add documentation for sensors](https://github.com/bluerobotics/navigator-rs/pull/15)
[Docs - Add documentation for structures](https://github.com/bluerobotics/navigator-rs/pull/16)

**Comment by RaulTrombin** [comment]
Pending two PR's:
[Docs - Add documentation for sensors](https://github.com/bluerobotics/navigator-rs/pull/15)
[Adc - Upgrades and doc](https://github.com/bluerobotics/navigator-rs/pull/17)
