### ISSUE TITLE
Add a local CI running on Raspberry with Navigator

### ISSUE THREAD

**Issue by RaulTrombin** [bluerobotics/navigator-rs#22]
We need to setup raspberry pi for organization, then we can use it for navigator-rs, navigator-lib and ak09

**Comment by RaulTrombin** [comment]
- [ ] https://github.com/bluerobotics/navigator-rs/pull/60
- [ ] https://github.com/bluerobotics/navigator-rs/pull/58
- [ ] https://github.com/bluerobotics/navigator-rs/pull/61

**Comment by patrickelectric** [comment]
Are they still in wip ?

**Comment by RaulTrombin** [comment]
@patrickelectric 
Suggest to create a group called: `Raspbian-armv7-51033` (the actual BlueOS kernel)
https://github.com/organizations/bluerobotics/settings/actions/runner-groups
