### ISSUE TITLE
Benchmark navigator's functions

### ISSUE THREAD

**Issue by RaulTrombin** [bluerobotics/navigator-rs#23]
Have a type of metric, some metrics from the current Master branch could be cached, then check improvements for every PR.

**Comment by joaoantoniocardoso** [comment]
Keeping track of the time each type of measurement takes seems a good start.

**Comment by RaulTrombin** [comment]
Sure! Maybe we can use [github-action-benchmark](https://github.com/benchmark-action/github-action-benchmark/tree/master)
But we need to run this locally first,
- [ ] https://github.com/bluerobotics/navigator-rs/issues/22

Ideas from git_actions's repo:
![image](https://github.com/bluerobotics/navigator-rs/assets/80598030/aec7d327-e925-48c7-a6e2-bea9d57950b5)
![image](https://github.com/bluerobotics/navigator-rs/assets/80598030/e9d72e28-fd3e-4672-81d6-8df6a8bd1c22)

**Comment by RaulTrombin** [comment]
Almost done with:

- [x] https://github.com/bluerobotics/navigator-rs/pull/53
- [ ] https://github.com/bluerobotics/navigator-rs/pull/58
- [ ] https://github.com/bluerobotics/navigator-rs/pull/61

**Comment by RaulTrombin** [comment]
@patrickelectric 
Suggest to create a group called: `Raspbian-armv7-51033` (the actual BlueOS kernel)
https://github.com/organizations/bluerobotics/settings/actions/runner-groups
